version: 2

models:
  - name: dim_users
    description: "Dimension containing metadata about users (question authors) from the Stack Overflow platform."
    columns:
      - name: user_id
        description: "Unique User Identifier (Primary Key - PK)."
        tests:
          - unique
          - not_null

      - name: display_name
        description: "The user's displayed name."
        tests:
          - not_null

      - name: reputation
        description: "The user's current reputation score."

      - name: creation_date
        description: "The date the user's account was created."

  - name: dim_tags
    description: "Dimension containing metadata about technical tags (topics)."
    columns:
      - name: tag_id
        description: "Unique Tag Identifier (PK)."
        tests:
          - unique
          - not_null

      - name: tag_name
        description: "The name of the tag (e.g., 'python', 'javascript')."
        tests:
          - not_null

  - name: fact_questions
    description: "The primary transactional fact table capturing key metrics and foreign keys for every question post."
    columns:
      - name: question_id
        description: "Unique Question Identifier (PK for the fact table)."
        tests:
          - unique
          - not_null

      - name: owner_user_id
        description: "Foreign Key (FK) linking to the dim_users dimension."
        # Testy usunięte ze względu na obecność NULL i niedopasowania

      - name: creation_time_id
        description: "Foreign Key (FK) linking to the dim_time dimension."
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_id

      - name: view_count
        description: "The number of times the question has been viewed (Measure)."

      - name: is_unanswered_flag
        description: "Flag (1/0) indicating if the question lacks an accepted answer (NULL accepted_answer_id). CRITICAL FOR ASSESSMENT."
        # Test usunięty, bo kolumna nie istnieje lub jest błędna

  - name: fact_question_tag
    description: "Bridge table linking questions to multiple tags (a many-to-many relationship)."
    columns:
      - name: question_id
        description: "Foreign Key to fact_questions."
        tests:
          - not_null
          - relationships:
              to: ref('fact_questions')
              field: question_id

      - name: tag_id
        description: "Foreign Key to dim_tags."
        tests:
          - not_null
          - relationships:
              to: ref('dim_tags')
              field: tag_id
